if has("mouse")
  set mouse=a
endif

set guifont=Monaco:h11
set antialias                     " MacVim: smooth fonts.
set guioptions-=T                 " Hide toolbar.
" set background=light               " Background.
" colorscheme solarized
set transparency=4
set go-=m go-=T go-=l go-=L go-=r go-=R go-=b go-=F
