" Set encoding
set encoding=utf-8

" " Use pathogen
" execute pathogen#infect()

" plugin manager
call plug#begin('~/.vim/plugged')
  Plug 'altercation/vim-colors-solarized'
  Plug 'amadeus/vim-mjml'
  Plug 'aredridel/html5'
  Plug 'chriskempson/base16-vim'
  Plug 'dracula/vim', { 'as': 'dracula' }
  Plug 'fatih/vim-go'
  Plug 'junegunn/goyo.vim'
  Plug 'junegunn/vader.vim',  { 'on': 'Vader', 'for': 'vader' }
  Plug 'kien/ctrlp.vim'
  Plug 'majutsushi/tagbar'
  Plug 'mileszs/ack.vim'
  Plug 'mxw/vim-jsx'
  Plug 'nathanaelkane/vim-indent-guides'
  Plug 'pangloss/vim-javascript'
  Plug 'scrooloose/nerdcommenter'
  Plug 'scrooloose/nerdtree'
  Plug 'slim-template/vim-slim'
  Plug 'tpope/vim-dispatch'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-projectionist'
  Plug 'tpope/vim-rails'
  Plug 'tpope/vim-rake'
  Plug 'tpope/vim-rhubarb'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-unimpaired'
  Plug 'tweekmonster/django-plus.vim'
  Plug 'valloric/youcompleteme'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Backspace key
set backspace=indent,eol,start

" Turn on line numbering
set nu

" Enable mouse
set mouse=a

" Turn on syntax highlighting
syntax on

" Show typing command
set showcmd

" Automatical indentation
filetype indent on
set autoindent

" Autocomplete with omni function
filetype plugin on
set ofu=syntaxcomplete

" no wrap
set nowrap

" Tab = 2 spaces
set tabstop=2

" Space for indentation
set shiftwidth=2

" Tab to spaces
set expandtab

" Show current line number and cursor position
set ruler

" Highlight current line
set cursorline

" Case insensitive search
set ic

" Highligh search
set hls

" Show partial match
set is

" Set terminal title
set title

" Show columns line
set colorcolumn=81,121,161

" Keep 3 lines when scrolling
set scrolloff=3

" Background
set background=dark

" Set Colorscheme
colorscheme dracula

" Set Python tab settings
autocmd FileType python setlocal tabstop=4 expandtab shiftwidth=4 softtabstop=4

" Use ruby syntax for thor script
autocmd BufRead,BufNewFile *.thor set filetype=ruby

" Use ruby syntax for riif script
autocmd BufWinEnter,BufRead,BufNewFile *.riif set filetype=ruby

" leaderkey
let mapleader = ","

" show buffer list
nnoremap <leader><Space> :buffers<CR>:buffer<Space>

" rspec 2 key binding
" nmap <F5> :!be rspec --no-color %<CR>

" NERDTree key binding
nmap <silent> <c-n> :NERDTreeToggle<CR>
" Show editing file in NERDTree
nmap <leader>l :NERDTreeFind<CR>
" Ignore temporary file listing in NERDTree
let NERDTreeIgnore=['.swp$', '\~$', '.bundle', '__pycache__', '.pyc$']

" CtrlP configuration
nmap <leader>. :CtrlPTag<CR>
set wildignore+=*/.git/*,*/node_modules/*
let g:ctrlp_max_depth = 8
let g:ctrlp_custom_ignore = {
  \   'dir':  '\v[\/]\.(git|hg|svn)$',
  \   'file': '\v\.(pyc|swp|so)$'
  \ }

" Navigate windows with ctrl direction
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l

" disable arrow keys
noremap  <Up> <Nop>
noremap  <Down> <Nop>
noremap  <Left> <Nop>
noremap  <Right> <Nop>

" Tab
nnoremap <Tab>l gt
nnoremap <Tab>h gT


" Go to definition
nmap <F6> g*<CR>

" Search
nmap <F3> :execute " grep -srnw --binary-files=without-match --exclude-dir={bin,log,.{hg,git,un~,swp,happypack,mrconfig},tags,node_modules} . -e " . expand("<cword>") . " " <bar> cwindow<CR>
nmap <F4> :execute " noautocmd vimgrep /" . expand("<cword>") . "/gj **/*.{" . expand('%:e') . ",yml,env}" <bar> cw<CR>

" Folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" BufExplorer settings
nnoremap <leader>f :bn<CR>
nnoremap <leader>b :bp<CR>

" Close xml tag [Ctrl-x Ctrl-o doesn't work]
" inoremap <lt>/ </<C-X><C-O>

" irb interactive_editor
if has("autocmd")
  " Restore cursor position
  autocmd BufReadPost * 
    \ if line("'\"") > 1 && line("'\"") <= line("$") | 
    \   exe "normal! g`\"" |
    \ endif
endif

" " vim-rspec
" let g:rspec_runner = "os_x_iterm2"
" let g:rspec_command="!bundle exec rspec {spec}"
" map <Leader>t :call RunCurrentSpecFile()<CR>
" map <Leader>s :call RunNearestSpec()<CR>
" map <Leader>l :call RunLastSpec()<CR>
" map <Leader>T :call RunAllSpecs()<CR>

" run-spec.vim
nnoremap <leader>t :RunSpec<CR>
nnoremap <leader>r :RunSpecLine<CR>
nnoremap <leader>e :RunSpecLastRun<CR>
nnoremap <leader>cr :RunSpecCloseResult<CR>


" All JSX in normal JS files
let g:jsx_ext_required = 0


" Nerd commenter configurations
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java = 1
" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

" Airline
let g:airline#extensions#tabline#enabled = 1

" Ag or Ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep --smart-case'
  cnoreabbrev ag Ack!
endif

" Tagbar
nmap <F8> :TagbarToggle<CR>

" Goyo
let g:goyo_width = 135
let g:goyo_linenr = 1

" Indent guides
nnoremap <leader>ig :IndentGuidesToggle<CR>
