" Set encoding
set encoding=utf-8

" Use pathogen
execute pathogen#infect()

" Backspace key
set backspace=indent,eol,start

" Turn on line numbering
set nu

" Enable mouse
set mouse=a

" Turn on syntax highlighting
syntax on

" Show typing command
set showcmd

" Automatical indentation
filetype indent on
set autoindent

" Autocomplete with omni function
filetype plugin on
set ofu=syntaxcomplete

" no wrap
set nowrap

" Tab = 2 spaces
set tabstop=2

" Space for indentation
set shiftwidth=2

" Tab to spaces
set expandtab

" Show current line number and cursor position
set ruler

" Highlight current line
set cursorline

" Case insensitive search
set ic

" Highligh search
set hls

" Show partial match
set is

" Set terminal title
set title

" Show columns line
set colorcolumn=81,141

" Keep 3 lines when scrolling
set scrolloff=3

" Background
set background=dark

" Set Colorscheme
colorscheme dracula

" Set Python tab settings
autocmd FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4

" Use ruby syntax for thor script
autocmd BufRead,BufNewFile *.thor set filetype=ruby

" Use ruby syntax for riif script
autocmd BufWinEnter,BufRead,BufNewFile *.riif set filetype=ruby

" leaderkey
let mapleader = ","

" show buffer list
nnoremap <leader><Space> :buffers<CR>:buffer<Space>

" rspec 2 key binding
" nmap <F5> :!be rspec --no-color %<CR>

" NERDTree key binding
nmap <silent> <c-n> :NERDTreeToggle<CR>
" # show editing file in NERDTree
nmap <leader>l :NERDTreeFind<CR>
" ignore temporary file listing in NERDTree
let NERDTreeIgnore=['.swp$', '\~$', '.bundle']

" Navigate windows with ctrl direction
noremap <C-J> <C-W>j
noremap <C-K> <C-W>k
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l

" disable arrow keys
noremap  <Up> <Nop>
noremap  <Down> <Nop>
noremap  <Left> <Nop>
noremap  <Right> <Nop>

" Tab
nnoremap <Tab>l gt
nnoremap <Tab>h gT


" Go to definition
nmap <F6> g*<CR>

" Search
nmap <F3> :execute " grep -srnw --binary-files=without-match --exclude-dir={bin,log,.{hg,git,un~,swp,tags,node_modules}} . -e " . expand("<cword>") . " " <bar> cwindow<CR>

" Folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

" BufExplorer settings
nnoremap <leader>f :bn<CR>
nnoremap <leader>b :bp<CR>

" Close xml tag [Ctrl-x Ctrl-o doesn't work]
" inoremap <lt>/ </<C-X><C-O>

" irb interactive_editor
if has("autocmd")
  " Restore cursor position
  autocmd BufReadPost * 
    \ if line("'\"") > 1 && line("'\"") <= line("$") | 
    \   exe "normal! g`\"" |
    \ endif
endif

" " vim-rspec
" let g:rspec_runner = "os_x_iterm2"
" let g:rspec_command="!bundle exec rspec {spec}"
" map <Leader>t :call RunCurrentSpecFile()<CR>
" map <Leader>s :call RunNearestSpec()<CR>
" map <Leader>l :call RunLastSpec()<CR>
" map <Leader>T :call RunAllSpecs()<CR>

" run-spec.vim
nnoremap <leader>t :RunSpec<CR>
nnoremap <leader>r :RunSpecLine<CR>
nnoremap <leader>e :RunSpecLastRun<CR>
nnoremap <leader>cr :RunSpecCloseResult<CR>


" vim-jsx configuration
let g:jsx_ext_required = 0
